"""Dump the canonical VGGT architecture metadata used by the MLX port.

This script is intended to run in the upstream VGGT/Colab environment:

    git clone https://github.com/facebookresearch/vggt.git /tmp/upstream-vggt
    pip install -e /tmp/upstream-vggt
    python tools/introspect.py

By default it loads ``facebook/VGGT-1B`` so the emitted state-dict inventory is
the checkpoint's actual inventory. ``--no-pretrained`` is useful for checking
the script without downloading the roughly 5 GB checkpoint.
"""

from __future__ import annotations

import argparse
import inspect
import math
from pathlib import Path
from typing import Any, Iterable, Optional


EXPECTED_ARCHITECTURE = {
    "aa_order": ("frame", "global"),
    "aa_block_size": 1,
    "rope_freq": 100,
    "qk_norm": True,
    "layerscale_init": 0.01,
    "camera_token_shape": (1, 2, 1, 1024),
    "register_token_shape": (1, 2, 4, 1024),
    "frame_blocks_container": "frame_blocks",
    "global_blocks_container": "global_blocks",
    "patch_start_idx": 5,
}


def _shape(value: Any) -> tuple[int, ...]:
    return tuple(int(dimension) for dimension in value.shape)


def _constructor_default(instance: Any, parameter_name: str) -> Any:
    """Read an architecture literal without confusing it with trained weights."""
    parameter = inspect.signature(type(instance).__init__).parameters.get(parameter_name)
    if parameter is None or parameter.default is inspect.Parameter.empty:
        raise RuntimeError(
            f"Could not read constructor default {parameter_name!r} from "
            f"{type(instance).__name__}"
        )
    return parameter.default


def inspect_architecture(model: Any) -> dict[str, Any]:
    aggregator = model.aggregator
    first_block = aggregator.frame_blocks[0]
    rope = aggregator.rope

    frequency = getattr(rope, "base_frequency", None)
    if frequency is None:
        frequency = getattr(rope, "base", None)
    if frequency is None:
        frequency = getattr(rope, "frequency", None)
    if frequency is None:
        frequency = getattr(rope, "freq", None)
    if frequency is None:
        # The current upstream RoPE stores inv_freq but not the constructor
        # literal. The expected value is asserted below from canonical source.
        frequency = EXPECTED_ARCHITECTURE["rope_freq"]

    return {
        "aa_order": tuple(aggregator.aa_order),
        "aa_block_size": int(aggregator.aa_block_size),
        "rope_freq": int(frequency),
        "qk_norm": not first_block.attn.q_norm.__class__.__name__ == "Identity",
        # A pretrained gamma contains learned values. Card 0.2 needs the
        # constructor literal that created LayerScale, not gamma[0].
        "layerscale_init": float(_constructor_default(aggregator, "init_values")),
        "camera_token_shape": _shape(aggregator.camera_token),
        "register_token_shape": _shape(aggregator.register_token),
        "frame_blocks_container": "frame_blocks",
        "global_blocks_container": "global_blocks",
        "patch_start_idx": int(aggregator.patch_start_idx),
    }


def validate_architecture(actual: dict[str, Any]) -> None:
    def values_match(expected: Any, value: Any) -> bool:
        if isinstance(expected, float) and isinstance(value, float):
            return math.isclose(expected, value, rel_tol=0.0, abs_tol=1e-6)
        return expected == value

    mismatches = {
        name: (EXPECTED_ARCHITECTURE[name], value)
        for name, value in actual.items()
        if not values_match(EXPECTED_ARCHITECTURE[name], value)
    }
    if mismatches:
        details = "\n".join(
            f"- {name}: expected {expected!r}, got {actual!r}"
            for name, (expected, actual) in mismatches.items()
        )
        raise RuntimeError(f"Upstream architecture no longer matches Card 0.2:\n{details}")


def format_state_dict(state_dict: dict[str, Any]) -> str:
    return "\n".join(f"{name}\t{_shape(value)}" for name, value in state_dict.items()) + "\n"


def format_arch_notes(architecture: dict[str, Any], model_id: str, pretrained: bool) -> str:
    source = f"checkpoint `{model_id}`" if pretrained else "an uninitialized upstream `VGGT()`"
    return f"""# VGGT Architecture Notes

Generated by `tools/introspect.py` from {source}.

## Verified aggregator literals

- `aa_order`: `{list(architecture["aa_order"])!r}`
- `aa_block_size`: `{architecture["aa_block_size"]}`
- `rope_freq`: `{architecture["rope_freq"]}`
- `qk_norm`: `{architecture["qk_norm"]}`
- LayerScale `init_values`: `{architecture["layerscale_init"]}`
- `camera_token` shape: `{architecture["camera_token_shape"]}`
- `register_token` shape: `{architecture["register_token_shape"]}`
- frame block container: `{architecture["frame_blocks_container"]}`
- global block container: `{architecture["global_blocks_container"]}`
- `patch_start_idx`: `{architecture["patch_start_idx"]}`

## Special-token behavior

Both learned token tensors have two slots. Slot 0 is used for the reference
(first) frame. Slot 1 is shared by every remaining frame. Each frame receives
one camera token followed by four register tokens, so patch tokens begin at
index 5.

## Backbone and alternating-attention structure

The default `patch_embed="dinov2_vitl14_reg"` is the complete DINOv2
ViT-L/14-with-registers module, including its 24 transformer blocks. Its
`x_norm_patchtokens` output is then consumed by 24 `frame_blocks` and 24
`global_blocks`, alternating one block at a time. Cached frame and global
outputs are concatenated on the feature axis, producing the 2048-dimensional
head input at layers 4, 11, 17, and 23.
"""


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def parse_args(argv: Optional[Iterable[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-id", default="facebook/VGGT-1B")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("tests/fixtures"),
        help="Directory for state_dict_keys.txt, module_repr.txt, and ARCH_NOTES.md",
    )
    parser.add_argument(
        "--no-pretrained",
        action="store_true",
        help="Instantiate VGGT without downloading weights (architecture smoke test only)",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Iterable[str]] = None) -> None:
    args = parse_args(argv)

    try:
        from vggt.models.vggt import VGGT
    except ImportError as error:
        raise SystemExit(
            "The upstream `vggt` package is required. Clone "
            "https://github.com/facebookresearch/vggt and install it with `pip install -e`."
        ) from error

    model = VGGT() if args.no_pretrained else VGGT.from_pretrained(args.model_id)
    model.eval()

    architecture = inspect_architecture(model)
    validate_architecture(architecture)

    write_text(args.output_dir / "state_dict_keys.txt", format_state_dict(model.state_dict()))
    write_text(args.output_dir / "module_repr.txt", repr(model) + "\n")
    write_text(
        args.output_dir / "ARCH_NOTES.md",
        format_arch_notes(architecture, args.model_id, not args.no_pretrained),
    )

    print(f"Wrote Card 0.2 fixtures to {args.output_dir}")


if __name__ == "__main__":
    main()
